- name: Install Thingsboard on Kubernetes KinD
  hosts: localhost
  tasks:

  - name: KinD Prerequisites
    shell: "sh /root/thingsboard/install/kind-prereq.sh"
    tags: installKind

  - name: KinD Installation
    shell: "sh /root/thingsboard/install/kind-install.sh"
    tags: installKind

  - name: Deploy NGINX Ingress
    shell: "sh /root/thingsboard/install/deploy-ingress.sh"
    tags: deployIngress

  - name: Deploy ArgoCD
    shell: "sh /root/thingsboard/install/deploy-argocd.sh"
    tags: deployArgocd

  - name: Expose ArgoCD with NGINX Ingress
    shell: "kubectl apply -f ingress.yaml"
    tags: deployArgocd

  - name: Clone Thingsboard Git Repository
    git:
      repo: https://github.com/thingsboard/thingsboard-ce-k8s.git
      version: release-3.6.2
      dest: /tmp/thingsboard
    tags: deployTb

  - name: Run Thingsboard Installation
    shell: "./k8s-install-tb.sh"
    args:
      chdir: /tmp/thingsboard/minikube
    tags: deployTb

  - name: Deploy Thingsboard Resources
    shell: "./k8s-deploy-resources.sh"
    args:
      chdir: /tmp/thingsboard/minikube
    tags: deployTb
