---
# tasks file for deploy-k8s-tb

- name: Install K3s
  ansible.builtin.import_tasks: 01_k3s.yaml
  tags: installK3s

- name: Deploy Ingress
  ansible.builtin.import_tasks: 02_ingress_nginx.yaml
  tags: deployIngress

- name: Deploy ArgoCD
  ansible.builtin.import_tasks: 03_deploy_argocd.yaml
  tags: deployArgocd

- name: Configure ArgoCD
  ansible.builtin.import_tasks: 04_configure_argocd.yaml
  tags: configureArgocd

- name: Show details to user
  ansible.builtin.import_tasks:  05_print_details.yaml
  tags: showDetails
